version: "3.7"
services:
  db:
    image: postgres:12
    ports:
      - 3333:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dsvendas
      POSTGRES_DB: dsvendas
      POSTGRES_PASSWORD: dsvendas

  back:
    build: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/app
    environment:
      APP_PROFILE: dev
    depends_on:
      - db
volumes:
  dbdata:
